[book]
authors = ["nd6k"]
language = "en"
multilingual = false
src = "src"
title = "Compsci Project API Documentation"

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = true

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/NaughtyDog6000/rust-backend/tree/main"