[book]
authors = ["nd6k"]
language = "en"
multilingual = false
src = "src"
title = "Compsci Project API Documentation"

[output.html]
default-theme = "coal"
git-repository-url = "https://github.com/NaughtyDog6000/rust-backend/tree/main"

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = true

[output.html.code.hidelines]
javascript = "///" 

[output.html.fold]
enable = true


