[book]
authors = ["nd6k"]
language = "en"
multilingual = false
src = "src"
title = "Compsci Project API Documentation"

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = true


[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = false     # displays line numbers for editable code
runnable = true          # displays a run button for rust code

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/NaughtyDog6000/rust-backend/tree/main"